Repository dandi/dandidav, pull requests merged in 2024-03, with the labels that each got.

#94 Add `--prefer-s3-redirects` CLI option
  CHANGELOG.md
  README.md
  src/dandi/types.rs
  src/dav/html.rs
  src/dav/mod.rs
  src/dav/types.rs
  src/main.rs
Labels: enhancement

#97 Don't show "commit" without hash in web view if commit hash not known
  src/dav/html.rs
Labels: ui:web, bugfix

#102 Use local timezone offset for log timestamps
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: logging

#104 Silence linting failure caused by async-trait
  src/dav/util.rs
  src/dav/xml/propfind.rs
  src/httputil.rs
Labels: code quality

#107 Revert "Fetch Git commit hash from `HEROKU_SLUG_COMMIT` if Git info not available"
  build.rs
Labels: deployment

#105 Heroku deployment configuration
  .github/workflows/deploy.yml
  Procfile
Labels: CI, deployment

#108 Add link to Dandi Archive instance to README
  README.md
Labels: documentation, skip deployment

#109 v0.3.0 — First Heroku deployment
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: release

#111 Set `Access-Control-Allow-Origin: *` header in all responses
  CHANGELOG.md
  src/main.rs
Labels: enhancement, HTTP protocol

#113 Revert "Silence linting failure caused by async-trait"
  src/dav/util.rs
  src/dav/xml/propfind.rs
  src/httputil.rs
Labels: code quality, skip deployment

#114 Delint
  src/zarrman/path.rs
Labels: code quality, skip deployment

#117 Add "skip deployment" label to Dependabot PRs
  .github/dependabot.yml
Labels: CI, skip deployment

#119 Set `--prefer-s3-redirects` in deployment
  Procfile
Labels: deployment
